section: screens
    jose-Vostro-3405:
    mint:
end

section: links
    jose-Vostro-3405:
        right = mint
    mint:
        left = jose-Vostro-3405
end

section: options
    relativeMouseMoves = false
    clipboardSharing = true
end
